spring:
  datasource:
    url: ${QUIZMI_DB_URL:jdbc:postgresql://localhost:5432/quizmi}
    username: ${QUIZMI_DB_USERNAME:quizmi}
    password: ${QUIZMI_DB_PASSWORD:quizmi}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

app:
  cors:
    allowed-origin-patterns: http://localhost:4200,http://127.0.0.1:4200,http://192.168.*:4200,http://10.*.*.*:4200
